import { builtinModules } from "node:module";
import { defineConfig } from "rolldown";

const production = process.env.BUILD === "production";
const builtins = new Set([
  ...builtinModules,
  ...builtinModules.map((moduleName) => `node:${moduleName}`),
]);

const external = [
  "obsidian",
  "electron",
  "@codemirror/autocomplete",
  "@codemirror/collab",
  "@codemirror/commands",
  "@codemirror/language",
  "@codemirror/lint",
  "@codemirror/search",
  "@codemirror/state",
  "@codemirror/view",
  "@lezer/common",
  "@lezer/highlight",
  "@lezer/lr",
  ...builtins,
];

const banner = `/*!
THIS IS A GENERATED/BUNDLED FILE BY ROLLDOWN
if you want to view the source, please visit the github repository of this plugin
*/
`;

export default defineConfig({
  input: "src/main.ts",
  external,
  platform: "browser",
  logLevel: "info",
  treeshake: true,
  tsconfig: "./tsconfig.json",
  transform: {
    target: "es2022",
  },
  output: {
    codeSplitting: false,
    file: "main.js",
    format: "cjs",
    banner,
    sourcemap: production ? false : "inline",
    minify: production,
  },
});
